const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto');
const html=fs.readFileSync(require('path').join(__dirname,'../index.html'),'utf8'),admin=fs.readFileSync(require('path').join(__dirname,'../house-admin.js'),'utf8'),scripts=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(m=>m[1]).filter(Boolean);
const context={console,crypto:crypto.webcrypto,Intl,Date,URLSearchParams,TextEncoder,Uint8Array,window:{addEventListener(){}},location:{hash:'',pathname:'/index.html'},sessionStorage:{getItem(){return null},setItem(){}},document:{getElementById:()=>null}};vm.createContext(context);
vm.runInContext(scripts[0],context);vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../konguta-admin.js'),'utf8'),context);
const run=s=>vm.runInContext(s,context);let n=0;function check(name,fn){fn();n++;console.log('PASS '+name)}
check('48 weekly Mondays for complete September–July season, same wall-clock dates across DST',()=>{const d=context.kBuildDates('2027-09-01','2028-07-31',1,[],true,'2027-09-01');assert.equal(d.dates.length,48);assert.equal(d.dates[0],'2027-09-06');assert.equal(d.dates.at(-1),'2028-07-31');assert.equal(d.dates.every(d=>context.kIsoWeekday(d)===1),true)});
check('Multi-day booking quote uses both dates and times',()=>{const fields={bookDate:{value:'2026-10-01'},bookEndDate:{value:'2026-10-02'},startTime:{value:'18:00'},endTime:{value:'22:00'},clientType:{value:'community'},bookRoom:{value:'konguta-saal'},serviceSound:{checked:false},serviceLights:{checked:false},serviceTechnician:{checked:false}};context.document.getElementById=id=>fields[id]||null;const q=run('getQuote()');assert.equal(q.valid,true);assert.equal(q.hours,28);assert.equal(q.roomCost,560);fields.bookEndDate.value='2026-09-30';assert.equal(run('bookingDuration()').valid,false)});
check('Refresh restores the last selected page from session state when the URL has no hash',()=>{let saved='activities';context.location={hash:'',pathname:'/index.html'};context.sessionStorage={getItem:key=>{assert.equal(key,'culturehub:last-view:/index.html');return saved},setItem:(key,value)=>{assert.equal(key,'culturehub:last-view:/index.html');saved=value}};assert.equal(run('routeView()'),'activities');context.location.hash='#rooms';assert.equal(run('routeView()'),'rooms')});
check('Current season skips past days and explicit holiday exceptions',()=>{const d=context.kBuildDates('2026-09-01','2027-07-31',4,['2026-12-24','2026-12-31'],false,'2026-09-27');assert.equal(d.skippedPast.length,4);assert.equal(d.dates.includes('2026-12-24'),false);assert.equal(d.dates[0],'2026-10-01')});
check('Invalid range and empty selection are blocked',()=>{assert.throws(()=>context.kBuildDates('2026-02-30','2026-03-05',1),/Kontrolli/);assert.throws(()=>context.kBuildDates('2026-09-01','2028-09-01',1),/hooaja/)});
check('Text quick entry parses collective, Estonian weekday, times and season',()=>{context.groups=[{id:'kavalik',name:'Segarühm Kavalik'}];const d=run("kExtractSchedule('Kavalik neljapäeviti 19.30–21.30, hooaeg 2026/27. Välja arvatud 24.12.2026.',groups,'2026-09-27')");assert.equal(d.collectiveId,'kavalik');assert.equal(d.weekday,4);assert.equal(d.startTime,'19:30');assert.equal(d.endDate,'2027-07-31');assert.equal(d.excludedDates[0],'2026-12-24')});
check('Missing times are not invented',()=>{const d=run("kExtractSchedule('Kavalik hooajaks 2026/27',groups,'2026-09-27')");assert.equal(d.endTime,undefined);assert.match(d.question,/lõpuaeg/)});
check('Each public page persists the active view for refresh',()=>{for(const file of ['index.html','test.html','rongu.html','valguta.html']){const source=fs.readFileSync(require('path').join(__dirname,'..',file),'utf8');assert.ok(source.includes("const VIEW_STORAGE_KEY='culturehub:last-view:'+location.pathname;"),file);assert.ok(source.includes('sessionStorage.setItem(VIEW_STORAGE_KEY,name)'),file)}});
check('Booking status badges stay compact instead of stretching into ovals',()=>{for(const file of ['index.html','test.html','rongu.html','valguta.html']){const source=fs.readFileSync(require('path').join(__dirname,'..',file),'utf8');assert.ok(source.includes('.booking-row-top{display:flex;align-items:flex-start;'),file);assert.ok(source.includes('.booking-row-top>.badge{align-self:flex-start;flex:0 0 auto;'),file)}});
check('Room image editor shows which room is selected and explains gallery count',()=>{assert.ok(admin.includes('Vali ruum. Avanev vorm muudab ainult selle ruumi'));assert.ok(admin.includes('Muudad praegu'));assert.ok(admin.includes('Need lisapildid kuuluvad ainult ruumile'));assert.ok(admin.includes('Galerii: ${items.length} / 6 pilti'));assert.ok(admin.includes('aria-pressed="${selected}"'))});
check('All public calendars clearly distinguish free, partial and fully occupied days',()=>{for(const file of ['index.html','test.html','rongu.html','valguta.html']){const source=fs.readFileSync(require('path').join(__dirname,'..',file),'utf8');assert.ok(source.includes('Vaba</span><span><i class="legend-partial"'),file);assert.ok(source.includes('Osaliselt hõivatud'),file);assert.ok(source.includes('Hõivatud</span>'),file);assert.ok(source.includes('.calendar-day.availability-free{background:#d9f0df;'),file);assert.ok(source.includes('.calendar-day.availability-partial{background:#ffedb5;'),file);assert.ok(source.includes('.calendar-day.availability-full{background:#f4c4bf;'),file)}});
check('All public booking forms expose and submit an end date',()=>{for(const file of ['index.html','test.html','rongu.html','valguta.html']){const source=fs.readFileSync(require('path').join(__dirname,'..',file),'utf8');assert.ok(source.includes('id="bookEndDate"'),file);assert.ok(source.includes("endDate:$('bookEndDate')?.value||$('bookDate').value"),file)}});
check('All new public content elements exist and module loads before startup',()=>{for(const id of ['homeTitle','homeDescription','homeNote','communityTitle','communityDescription','activitiesDescription','contactAddress','contactEmail','contactPhone','bookingConfirmationHint','eventBookingHint'])assert.ok(html.includes('id="'+id+'"'),id);assert.ok(html.indexOf('src="konguta-admin.js')<html.indexOf("$('eventDate').value=etDate();eventCalendarMonth=etDate().slice(0,7);bookingCalendarMonth="))});
for(const s of scripts)new vm.Script(s);console.log(`${n} frontend checks passed.`);

check('Public event list excludes rehearsals, private bookings and pending events; calendar keeps all uses',()=>{
 const source=[{type:'Proov',publicEvent:true,publicTitle:'Kooriproov'},{type:'Sündmus',publicEvent:true,publicTitle:'Kontsert'},{type:'broneering',publicEvent:false,publicTitle:'Salajane sünnipäev'},{type:'Sündmus',publicEvent:true,status:'ootel',publicTitle:'Ootel üritus'}].map(x=>({roomId:'konguta-saal',date:'2027-10-01',startTime:'18:00',endTime:'20:00',status:'kinnitatud',...x}));
 const snapshot=context.publicCalendarUsages(source);assert.equal(snapshot.length,4);assert.equal(context.snapshotDay(snapshot,'2027-10-01').length,4);const events=context.upcomingPublicEvents(snapshot,'2027-09-28');assert.equal(events.length,1);assert.equal(events[0].title,'Kontsert');assert.equal(snapshot[2].title,'Ruum kasutuses');
});
check('Occupancy dates include preparation before events and cleanup after midnight',()=>{
 const snapshot=context.publicCalendarUsages([{roomId:'konguta-saal',date:'2026-10-12',endDate:'2026-10-13',startTime:'18:00',endTime:'01:00',occupancyStartDate:'2026-10-12',occupancyStartTime:'15:00',occupancyEndDate:'2026-10-13',occupancyEndTime:'11:00',status:'kinnitatud',publicEvent:false}]);
 const before=context.snapshotDay(snapshot,'2026-10-12','konguta-saal'),after=context.snapshotDay(snapshot,'2026-10-13','konguta-saal');
 assert.equal(before.length,1);assert.equal(before[0].startTime,'15:00');assert.equal(before[0].endTime,'24:00');
 assert.equal(after.length,1);assert.equal(after[0].startTime,'00:00');assert.equal(after[0].endTime,'11:00');
 assert.equal(context.roomAvailability(before,'konguta-saal').code,'partial');
});
check('House admin exposes standalone occupancy, selected rooms and configurable whole-house scope',()=>{
 new vm.Script(admin);assert.ok(admin.includes("function kOpenOccupancy(bookingId='',initialDate=etDate())"));assert.ok(admin.includes("scope==='rooms'"));assert.ok(admin.includes('occupancyRoomIds'));assert.ok(admin.includes('kEditOccupancyStartDate'));
});
check('Staff workspace restores full width whenever it renders',()=>{const render=admin.match(/function kRenderStaff\(\)\{([\s\S]*?)\n\}/)?.[1];assert.ok(render);assert.ok(render.includes("$('staffPanel').parentElement.style.maxWidth='none'"));});
check('Calendar loading success and failures rerender the calendar tab',()=>{const fn=admin.match(/function kWorkspaceSectionIsActive\(section\)\{[^}]+\}/)?.[0];assert.ok(fn);const sandbox=vm.createContext({kStaffTab:'calendar'});vm.runInContext(fn,sandbox);assert.equal(vm.runInContext("kWorkspaceSectionIsActive('bookings')",sandbox),true);assert.equal(vm.runInContext("kWorkspaceSectionIsActive('contracts')",sandbox),false);assert.ok(admin.includes('else if(kWorkspaceSectionIsActive(section))kRenderStaff()'));assert.ok(admin.includes('else if(kWorkspaceSectionIsActive(section)&&$(\'kStaffSection\'))'));assert.ok(admin.includes('kEnsureWorkspaceSection(\'${section}\',true)'))});
check('Mobile menu ends with culture screen and keeps staff access in header',()=>{const nav=html.match(/<nav class="mobile-nav"[\s\S]*?<\/nav>/)[0];assert.ok(nav.indexOf('Huviringid')<nav.indexOf('Kultuuriekraan'));assert.ok(!nav.includes('Töötajale'));assert.ok(html.includes('mobile-staff'));});
check('Back follows actual internal history and preserves in-memory booking fields',()=>{
 const listeners={},views=['home','events','booking','activities','rooms','contact','login'];const elements={};
 for(const id of views.map(v=>'view-'+v).concat(['bookingBack','bookingForm','clientName','clientEmail','bookDate']))elements[id]={classList:{add(){},remove(){},toggle(){}},querySelector:()=>null,value:'',textContent:''};
 elements.clientName.value='Test Client';elements.clientEmail.value='client@example.test';
 context.document.getElementById=id=>elements[id]||null;context.document.querySelectorAll=selector=>selector==='.view'?views.map(v=>elements['view-'+v]):[];
 context.window.scrollTo=()=>{};context.location={hash:'#home'};const stack=[];context.history={state:null,pushState(state,_,hash){stack.push({state:this.state,hash:context.location.hash});this.state=state;context.location.hash=hash;},replaceState(state,_,hash){this.state=state;context.location.hash=hash;},back(){const last=stack.pop();this.state=last.state;context.location.hash=last.hash;context.showView(context.routeView(),true);}};
 run("loadHomeEvents=()=>{};loadEventSchedule=()=>{};renderRegularActivities=()=>{};loadBookingSchedule=()=>{};loadCollectives=()=>{};renderRooms=()=>{};");
 context.initNavigation();assert.equal(elements.bookingBack.textContent,'← Avalehele');context.showView('events');context.showView('booking');assert.equal(context.location.hash,'#booking');assert.equal(elements.bookingBack.textContent,'← Tagasi');context.goBookingBack();assert.equal(context.location.hash,'#events');assert.equal(elements.clientName.value,'Test Client');assert.equal(elements.clientEmail.value,'client@example.test');
 context.showView('booking');context.showView('rooms');context.history.back();assert.equal(context.location.hash,'#booking');assert.equal(elements.clientName.value,'Test Client');
});
check('Direct booking link has a safe home fallback',()=>{context.location.hash='#booking';context.history.state=null;context.initNavigation();assert.equal(context.document.getElementById('bookingBack').textContent,'← Avalehele');context.goBookingBack();assert.equal(context.location.hash,'#home');});
console.log(`${n} total frontend checks passed.`);
